name: Daily Checkin

on:
  workflow_dispatch: 
  schedule:
    - cron: '17 22 * * *'

jobs:
  run_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyotp playwright playwright-stealth

      - name: Install Playwright Browsers
        # 核心改动：使用 python 自己的安装器
        run: python -m playwright install chromium --with-deps

      - name: Run script
        env:
          IKUUU_EMAIL: ${{ secrets.IKUUU_EMAIL }}
          IKUUU_PASSWORD: ${{ secrets.IKUUU_PASSWORD }}
          IKUUU_2FA_SECRET: ${{ secrets.IKUUU_2FA_SECRET }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python main.py
